### ISSUE TITLE
En el readme falta el indice o index a cada sección

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-alfei-cabral#2]
El mismo se implementa de la siguiente manera:
```
- [Alumnos](#alumnos)
- [Descripción](#descripción)
  - [Tecnologías Usadas](#tecnologías-usadas)
```

![imagen](https://github.com/UCC-LabCompu2/proyecto2024-alfei-cabral/assets/8345007/950c579f-6574-474e-b9cc-a3eb6f9b1ee4)

**Comment by juan-cabra1** [comment]
se agrego indice a cada seccion
