### ISSUE TITLE
Sugerencia: Mejorar el código JS

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-alfei-cabral#20]
https://github.com/UCC-LabCompu2/proyecto2024-alfei-cabral/blob/b31f3a8cd69da1cda47865b489a629a4759a1f39/Funciones.js#L271-L289

No es necesario tener tantos "if".
Se podría resolver más fácil como:
```
    if (horarioReserva && ciudadReserva && deporteReserva && fechaReserva) {
        ctx.fillText(`Horario: ${horarioReserva}`, 20, 30)
        ctx.fillText(`Ciudad: ${ciudadReserva}`, 20, 60);
        ctx.fillText(`Deporte: ${deporteReserva}`, 20, 90);
        ctx.fillText(`Fecha: ${fechaReserva}`, 20, 120);
    } else {
        console.error('No se encontró el canvas con ID "infoReservaCanvas".');
    }
```

Si todos los margenesX son 20, es conveniente asignarlo en una variable y no andarlo repitiendo constantemente.
En cuanto a la altura Y, sería mejor crearla como una constante=30, y que en cada renglón sea: margenY*1,margenY*2,margenY*3,margenY*4 (para que sea, 30,60,90,120)

**Comment by juan-cabra1** [comment]
profe este issue ya lo habiamos solucionado :)
